(ns slekt.language)

(def english
  {:events "Events"
   :birth "Birth"
   :baptism "Baptism"
   :marriage "Wedding"
   :census "Census"
   :death "Death"
   :burial "Burial"
   :place "Place"
   :child "Child"
   :father "Father"
   :mother "Mother"
   :husband "Husband"
   :wife "Wife"
   :spouse "Spouse"
   :children "Children"
   :son "Son"
   :daughter "Daughter"
   :unknown "Unknown"
   :spouse-with-children "Spouses and children"
   :bapm-event "Source: Birth/baptism"
   :buri-event "Source: Death/burial"
   :marr-event "Source: Marriage"
   :cens-event "Source: Census"
   })

(def norsk
  {
   :age "Alder"
   :baptism "Dåp"
   :birth "Fødsel"
   :burial "Begravelse"
   :button-cancel "Avbryt"
   :button-ok "OK"
   :census "Folketelling"
   :child "Barn"
   :children "Barn"
   :date "Dato"
   :daughter "Datter"
   :death "Død"
   :events "Hendelser"
   :event-bapm "Kilde: Fødsel/dåp"
   :event-buri "Kilde: Død/begravelse"
   :event-cens "Kilde: Folketelling"
   :event-marr "Kilde: Giftemål"
   :father "Far"
   :firstname "Fornavn"
   :husband "Mann"
   :lastname "Etternavn"
   :marriage "Giftemål"
   :mother "Mor"
   :persons-household "Personer i husstanden"
   :place "Sted"
   :role "Rolle"
   :select "Velg ..."
   :son "Sønn"
   :spouse "Ektefelle"
   :spouse-with-children "Ektefeller og barn"
   :unknown "Ukjent"
   :wife "Kone"

   ;; Month-names
   :jan "Januar"
   :feb "Februar"
   :mar "Mars"
   :apr "April"
   :may "Mai"
   :jun "Juni"
   :jul "Juli"
   :aug "August"
   :sep "September"
   :oct "Oktober"
   :nov "November"
   :dec "Desember"
   })