(ns slekt.language)

(def english
  {:events "Events"
   :birth "Birth"
   :baptism "Baptism"
   :marriage "Wedding"
   :census "Census"
   :death "Death"
   :burial "Burial"
   :place "Place"
   :child "Child"
   :father "Father"
   :mother "Mother"
   :husband "Husband"
   :wife "Wife"
   :spouse "Spouse"
   :children "Children"
   :son "Son"
   :daughter "Daughter"
   :unknown "Unknown"
   :spouse-with-children "Spouses and children"
   :bapm-event "Source: Birth/baptism"
   :buri-event "Source: Death/burial"
   :marr-event "Source: Marriage"
   :cens-event "Source: Census"
   })

(def norsk
  {:events "Hendelser"
   :birth "Fødsel"
   :baptism "Dåp"
   :marriage "Giftemål"
   :census "Folketelling"
   :death "Død"
   :burial "Begravelse"
   :place "Sted"
   :child "Barn"
   :father "Far"
   :mother "Mor"
   :husband "Mann"
   :wife "Kone"
   :spouse "Ektefelle"
   :children "Barn"
   :son "Sønn"
   :daughter "Datter"
   :unknown "Ukjent"
   :spouse-with-children "Ektefeller og barn"
   :bapm-event "Kilde: Fødsel/dåp"
   :buri-event "Kilde: Død/begravelse"
   :marr-event "Kilde: Giftemål"
   :cens-event "Kilde: Folketelling"
   :ok "OK"
   :cancel "Avbryt"
   :select "Velg ..."
   :firstname "Fornavn"
   :lastname "Etternavn"
   :persons-household "Personer i husstanden"
   })